# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.5
  - nightly
os:
  - linux
  - osx
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
addons:
  apt:
    packages:
      - python3-numpy
before_install:
  - pip3 install --user --upgrade pip
  - pip3 --version
  - pip3 install --user pyvista
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.5
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: doctest
          using RoughSurface
          doctest(RoughSurface)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
